const navstyles = {
  root_open: {
    width: 220,
    transition: 'width 0.3s',
    overflowX: 'hidden',
    bgcolor: '#4F0C24',
    overflow: 'hidden',
    color: 'white',
  },
  root_closed: {
    width: 60,
    transition: 'width 0.3s',
    overflowX: 'hidden',
    bgcolor: '#4F0C24',
    overflow: 'hidden',
    color: 'white',
  },
  list: { height: '100%', display: 'flex', flexDirection: 'column' },
  titlebox: {
    paddingX: 0,
    paddingBottom: 4,
    marginTop: 2,
    marginBottom: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 1,
  },
  title: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    display: 'flex',
    justifyContent: 'center',
    width: 48,
    height: 48,
  },
  arrow: { justifyContent: 'right', marginBottom: 6, marginTop: 'auto' },
  option: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingX: 0,
    paddingY: 0,
    borderBottom: '1px solid #FFFFFF',
    borderTop: '1px solid #FFFFFF',
  },
  pathtitle: {
    bgcolor: '#761236',
    color: '#FFFFFF',
    textDecoration: 'none',
    width: '100%',
    display: 'flex',
    paddingLeft: 0.5,
    paddingY: 1,
    borderBottom: '1px solid #FFFFFF',
  },
  pathtitle_hover: {
    bgcolor: '#761236',
    color: '#999999',
    textDecoration: 'none',
    width: '100%',
    display: 'flex',
    paddingLeft: 0.5,
    paddingY: 1,
    borderBottom: '1px solid #FFFFFF',
  },
  pathicon: {
    display: 'flex',
    marginRight: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subpath: {
    display: 'flex',
    justifyContent: 'center',
    color: '#FFFFFF',
    textDecoration: 'none',
    paddingY: 1.5,
    '&:hover': {
      color: '#999999',
    },
    marginX: 'auto',
    width: '90%',
  },
}

export default navstyles
