const GET_USER_DETAILS_END_POINT = "profile/";
const UPDATE_USER_DETAILS_END_POINT = "auth/user-details/";
const UPDATE_USER_SUBJECT_END_POINT = "profile/update/fav-sub";
const GET_LIBRARY_CARDS_END_POINT = "profile/get/library-card-details";

export { GET_USER_DETAILS_END_POINT, UPDATE_USER_DETAILS_END_POINT, UPDATE_USER_SUBJECT_END_POINT, GET_LIBRARY_CARDS_END_POINT };